//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class fines
    {
        public int id { get; set; }
        public string status { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
    }
}
