//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApp.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gibddEntities : DbContext
    {
        public gibddEntities()
            : base("name=gibddEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<driverPhoto> driverPhoto { get; set; }
        public virtual DbSet<drivers> drivers { get; set; }
        public virtual DbSet<fines> fines { get; set; }
        public virtual DbSet<licences> licences { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<vehicles> vehicles { get; set; }
        public virtual DbSet<regionCodes> regionCodes { get; set; }
    }
}
