//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverPhoto
    {
        public int pid { get; set; }
        public string filename { get; set; }
        public byte[] image_data { get; set; }
    }
}
