//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class regionCodes
    {
        public string Region_name_EN { get; set; }
        public string Region_name_RU { get; set; }
        public string Subject_code { get; set; }
        public string Code { get; set; }
        public string OKATO_code { get; set; }
        public string ISO_3166_2 { get; set; }
    }
}
