//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int uid { get; set; }
        public string uname { get; set; }
        public string upass { get; set; }
    }
}
